name: Build Sam APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # 17 se 21 kar diya taaki compile error na aaye

      - name: Install and Fix Frontend
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install ajv --save-dev

      - name: Build React app
        run: |
          cd frontend
          CI=false npm run build

      - name: Capacitor sync
        run: |
          cd frontend
          npx cap sync android

      - name: Build Debug APK
        run: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-assistant-debug
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7


